 
title: "Hepatotoxicity Displays and Analyses"
editor: visual
 
project:
  type: website
  output-dir: docs

website:
  title: "Hepatotox TLG Catalog"
  site-url: https://phuse-org.github.io/hepatotox/
  repo-url: https://github.com/phuse-org/hepatotox
  search: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Tables
        menu:
          - href: tables/table01.qmd
            text: Table 1 – Overview of Reported Liver Safety Findings
          - href: tables/table02.qmd
            text: Table 2 – Elevations in Liver Biochemical Tests Based on Thresholds
          - href: tables/table03.qmd
            text: Table 3 – Shifts in Liver Biochemical Tests Based on Thresholds
          - href: tables/table04.qmd
            text: Table 4 – Summary of Treatment Emergent Adverse Events of Adverse Events Meeting the Liver Safety SMQ (or FMQ)
      - text: Figures
        menu:
          - href: figures/figure01.qmd
            text: Figure 1 – Plot of Maximum Total Bilirubin Versus Maximum ALT or AST or ALP
          - href: figures/figure02.qmd
            text: Figure 2 – Scatterplot of Baseline Versus Maximum Values for Liver Biochemical Tests
          - href: figures/figure03.qmd
            text: Figure 3 – Line Plot for Liver Biochemical Tests
          - href: figures/figure04.qmd
            text: Figure 4 – Forest Plot of DILI Adverse Events Based on the SMQ (or FMQ)
          - href: figures/figure05.qmd
            text: Figure 5 – Patient Profiles of Subjects of Interest
    right:
      - icon: github
        href: https://github.com/phuse-org/hepatotox

format:
  html:
    theme: lumen
    toc: false
    code-copy: true
    code-fold: true
    tabsets: true
    highlight-style: tango
