project:
  type: website
  output-dir: docs

website:
  title: "Hepatotox Catalog"
  navbar:
    pinned: true         
    background: primary  
    foreground: light    
    left:
      - href: index.qmd
        text: Home
      - text: Articles
        menu:
          - href: introduction.qmd
            text: Introduction
          - href: liver-enzyme.qmd
            text: Liver Enzymes
      - text: Tables
        menu:
          - href: table01.qmd
            text: Table 01
          - href: table02.qmd
            text: Table 02
      - text: Figures
        menu:
          - href: figure01.qmd
            text: Figure 01
          - href: figure02.qmd
            text: Figure 02
      - href: resources.qmd
        text: Resources

format:
  html:
    theme: cosmo
