project:
  type: website
  output-dir: docs

website:
  title: "hepsite"
  navbar:
    left:
      - href: index.html
        text: Home
      - text: Tables
        menu:
          - href: table01.html
            text: Table 01
          - href: table02.html
            text: Table 02
          - href: table03.html
            text: Table 03
          - href: table04.html
            text: Table 04
      - text: Figures
        menu:
          - href: figure01.html
            text: Figure 01
          - href: figure02.html
            text: Figure 02
          - href: figure03.html
            text: Figure 03
          - href: figure04.html
            text: Figure 04
          - href: figure05.html
            text: Figure 05
      - text: Articles
        menu:
          - href: intro.html
            text: Intro to Hepatotox
          - href: liver.html
            text: Liver Enzymes Overview
          - href: resources.html
            text: Resources
      - about.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
